package br.com.morgado.barbershop.api.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class CupomDTO {

    //EXEMPLO DE UM DTO DATA TRANSFER OBJECT
    //OBJETOS DO TIPO DTO TEM A FINALIDADE DE OBTER DADOS DO FRONTEND, PROCESSAR E RETORNAR OUTRO DTO.
    //AS VEZES UM OBJETO DTO PODE SE TRANSFORMAR EM UM OBJETO MODEL
    //POR EXEMPLO: UM OBJETO DTO CONTEM INFORMACOES DE UM FORMULARIO E ESSAS INFORMACOES DEPOIS DE PASSAR POR UMA VALIDACAO
    //PODEMOS CRIAR UM OBJETO MODEL PARA RECEBER ESSES DADOS DO OBJETO DTO
    //ASSIM O OBJETO MODEL OU ENTITY PODE SER PERSISTIDO NO BANCO DE DADOS COM SEGURANCA

    private String numSerie;
    private String numCupom;

}
